### Hello

GET http://localhost:3000


### Cadastrar aluno
POST  http://localhost:3000/estudantes
Content-Type: application/json

{
  "nome": "Cassia",
  "endereco":"tao,tao,distante",
  "telefone":"82564264268",
  "email":"aquele@gmail.com",
  "anoNascimento": 1993
}